services:
  # PHP with Apache service
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:NMsF+GQGj9NmKZUEP2ngUQ8SdYLYb4FL88zGXs34ByM=
    depends_on:
      - db
    networks:
      - laravel-network
    restart: unless-stopped

  # MySQL service
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - laravel-network
    restart: unless-stopped

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
