services:
  # PHP with Apache service
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      # Use delegated mode for performance on Windows
      - "./:/var/www/html:delegated"
      - "./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:delegated"
      - "./.docker/php/php.ini:/usr/local/etc/php/php.ini:delegated"
      # Cache composer data to improve performance
      - composer-cache:/root/.composer/cache
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - APP_ENV=local
      # Reduced debugging output for better performance
      - APP_DEBUG=false
      - APP_KEY=base64:NMsF+GQGj9NmKZUEP2ngUQ8SdYLYb4FL88zGXs34ByM=
    depends_on:
      - db
    networks:
      - laravel-network
    restart: unless-stopped

  # MySQL service
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network
    restart: unless-stopped

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=laravel
      - PMA_PASSWORD=password
    depends_on:
      - db
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
  composer-cache:
